/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'id' : QuestionId,
  'status' : VoteStatus,
  'title' : string,
  'description' : string,
  'closedAt' : [] | [Timestamp],
  'raisedAt' : Timestamp,
  'raisedBy' : UserId,
  'selectedSubmission' : [] | [UserId],
  'roomCode' : RoomCode,
}
export type QuestionId = bigint;
export type QuestionResult = { 'ok' : Question } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type RaiseResult = { 'ok' : Question } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type RoomCode = string;
export interface RoomView {
  'creator' : UserId,
  'members' : Array<UserId>,
  'code' : RoomCode,
  'createdAt' : Timestamp,
  'memberCount' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type VoteChoice = { 'no' : null } |
  { 'yes' : null };
export type VoteResult = { 'ok' : null } |
  { 'votingClosed' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type VoteStatus = { 'closed' : null } |
  { 'open' : null };
export interface VoteSummary {
  'status' : VoteStatus,
  'title' : string,
  'yesPercent' : bigint,
  'noCount' : bigint,
  'totalVotes' : bigint,
  'yesCount' : bigint,
  'description' : string,
  'myVote' : [] | [VoteChoice],
  'questionId' : QuestionId,
  'noPercent' : bigint,
  'selectedSubmission' : [] | [UserId],
}
export interface _SERVICE {
  'castVote' : ActorMethod<[QuestionId, VoteChoice], VoteResult>,
  'closeVoting' : ActorMethod<[QuestionId], QuestionResult>,
  'createRoom' : ActorMethod<[], RoomView>,
  'getRoom' : ActorMethod<[RoomCode], [] | [RoomView]>,
  'getVoteSummary' : ActorMethod<[QuestionId], [] | [VoteSummary]>,
  'joinRoom' : ActorMethod<[RoomCode], [] | [RoomView]>,
  'listMyRooms' : ActorMethod<[], Array<RoomView>>,
  'listRoomQuestions' : ActorMethod<[RoomCode], Array<VoteSummary>>,
  'raiseQuestion' : ActorMethod<[RoomCode, string, string], RaiseResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];