/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionId = IDL.Nat;
export const VoteChoice = IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null });
export const VoteResult = IDL.Variant({
  'ok' : IDL.Null,
  'votingClosed' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const VoteStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const RoomCode = IDL.Text;
export const Question = IDL.Record({
  'id' : QuestionId,
  'status' : VoteStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'closedAt' : IDL.Opt(Timestamp),
  'raisedAt' : Timestamp,
  'raisedBy' : UserId,
  'selectedSubmission' : IDL.Opt(UserId),
  'roomCode' : RoomCode,
});
export const QuestionResult = IDL.Variant({
  'ok' : Question,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const RoomView = IDL.Record({
  'creator' : UserId,
  'members' : IDL.Vec(UserId),
  'code' : RoomCode,
  'createdAt' : Timestamp,
  'memberCount' : IDL.Nat,
});
export const VoteSummary = IDL.Record({
  'status' : VoteStatus,
  'title' : IDL.Text,
  'yesPercent' : IDL.Nat,
  'noCount' : IDL.Nat,
  'totalVotes' : IDL.Nat,
  'yesCount' : IDL.Nat,
  'description' : IDL.Text,
  'myVote' : IDL.Opt(VoteChoice),
  'questionId' : QuestionId,
  'noPercent' : IDL.Nat,
  'selectedSubmission' : IDL.Opt(UserId),
});
export const RaiseResult = IDL.Variant({
  'ok' : Question,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});

export const idlService = IDL.Service({
  'castVote' : IDL.Func([QuestionId, VoteChoice], [VoteResult], []),
  'closeVoting' : IDL.Func([QuestionId], [QuestionResult], []),
  'createRoom' : IDL.Func([], [RoomView], []),
  'getRoom' : IDL.Func([RoomCode], [IDL.Opt(RoomView)], ['query']),
  'getVoteSummary' : IDL.Func([QuestionId], [IDL.Opt(VoteSummary)], ['query']),
  'joinRoom' : IDL.Func([RoomCode], [IDL.Opt(RoomView)], []),
  'listMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'listRoomQuestions' : IDL.Func([RoomCode], [IDL.Vec(VoteSummary)], ['query']),
  'raiseQuestion' : IDL.Func([RoomCode, IDL.Text, IDL.Text], [RaiseResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionId = IDL.Nat;
  const VoteChoice = IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null });
  const VoteResult = IDL.Variant({
    'ok' : IDL.Null,
    'votingClosed' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const VoteStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const RoomCode = IDL.Text;
  const Question = IDL.Record({
    'id' : QuestionId,
    'status' : VoteStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'closedAt' : IDL.Opt(Timestamp),
    'raisedAt' : Timestamp,
    'raisedBy' : UserId,
    'selectedSubmission' : IDL.Opt(UserId),
    'roomCode' : RoomCode,
  });
  const QuestionResult = IDL.Variant({
    'ok' : Question,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const RoomView = IDL.Record({
    'creator' : UserId,
    'members' : IDL.Vec(UserId),
    'code' : RoomCode,
    'createdAt' : Timestamp,
    'memberCount' : IDL.Nat,
  });
  const VoteSummary = IDL.Record({
    'status' : VoteStatus,
    'title' : IDL.Text,
    'yesPercent' : IDL.Nat,
    'noCount' : IDL.Nat,
    'totalVotes' : IDL.Nat,
    'yesCount' : IDL.Nat,
    'description' : IDL.Text,
    'myVote' : IDL.Opt(VoteChoice),
    'questionId' : QuestionId,
    'noPercent' : IDL.Nat,
    'selectedSubmission' : IDL.Opt(UserId),
  });
  const RaiseResult = IDL.Variant({
    'ok' : Question,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  
  return IDL.Service({
    'castVote' : IDL.Func([QuestionId, VoteChoice], [VoteResult], []),
    'closeVoting' : IDL.Func([QuestionId], [QuestionResult], []),
    'createRoom' : IDL.Func([], [RoomView], []),
    'getRoom' : IDL.Func([RoomCode], [IDL.Opt(RoomView)], ['query']),
    'getVoteSummary' : IDL.Func(
        [QuestionId],
        [IDL.Opt(VoteSummary)],
        ['query'],
      ),
    'joinRoom' : IDL.Func([RoomCode], [IDL.Opt(RoomView)], []),
    'listMyRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'listRoomQuestions' : IDL.Func(
        [RoomCode],
        [IDL.Vec(VoteSummary)],
        ['query'],
      ),
    'raiseQuestion' : IDL.Func(
        [RoomCode, IDL.Text, IDL.Text],
        [RaiseResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };