/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type QuestionResult = {
    __kind__: "ok";
    ok: Question;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type UserId = Principal;
export type Timestamp = bigint;
export type QuestionId = bigint;
export interface RoomView {
    creator: UserId;
    members: Array<UserId>;
    code: RoomCode;
    createdAt: Timestamp;
    memberCount: bigint;
}
export type RoomCode = string;
export interface Question {
    id: QuestionId;
    status: VoteStatus;
    title: string;
    description: string;
    closedAt?: Timestamp;
    raisedAt: Timestamp;
    raisedBy: UserId;
    selectedSubmission?: UserId;
    roomCode: RoomCode;
}
export interface VoteSummary {
    status: VoteStatus;
    title: string;
    yesPercent: bigint;
    noCount: bigint;
    totalVotes: bigint;
    yesCount: bigint;
    description: string;
    myVote?: VoteChoice;
    questionId: QuestionId;
    noPercent: bigint;
    selectedSubmission?: UserId;
}
export type RaiseResult = {
    __kind__: "ok";
    ok: Question;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export enum VoteChoice {
    no = "no",
    yes = "yes"
}
export enum VoteResult {
    ok = "ok",
    votingClosed = "votingClosed",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export enum VoteStatus {
    closed = "closed",
    open = "open"
}
export interface backendInterface {
    castVote(questionId: QuestionId, choice: VoteChoice): Promise<VoteResult>;
    closeVoting(questionId: QuestionId): Promise<QuestionResult>;
    createRoom(): Promise<RoomView>;
    getRoom(code: RoomCode): Promise<RoomView | null>;
    getVoteSummary(questionId: QuestionId): Promise<VoteSummary | null>;
    joinRoom(code: RoomCode): Promise<RoomView | null>;
    listMyRooms(): Promise<Array<RoomView>>;
    listRoomQuestions(roomCode: RoomCode): Promise<Array<VoteSummary>>;
    raiseQuestion(roomCode: RoomCode, title: string, description: string): Promise<RaiseResult>;
}
import type { Question as _Question, QuestionId as _QuestionId, QuestionResult as _QuestionResult, RaiseResult as _RaiseResult, RoomCode as _RoomCode, RoomView as _RoomView, Timestamp as _Timestamp, UserId as _UserId, VoteChoice as _VoteChoice, VoteResult as _VoteResult, VoteStatus as _VoteStatus, VoteSummary as _VoteSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async castVote(arg0: QuestionId, arg1: VoteChoice): Promise<VoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.castVote(arg0, to_candid_VoteChoice_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_VoteResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.castVote(arg0, to_candid_VoteChoice_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_VoteResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async closeVoting(arg0: QuestionId): Promise<QuestionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.closeVoting(arg0);
                return from_candid_QuestionResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeVoting(arg0);
            return from_candid_QuestionResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoom(): Promise<RoomView> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom();
            return result;
        }
    }
    async getRoom(arg0: RoomCode): Promise<RoomView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoom(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoom(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoteSummary(arg0: QuestionId): Promise<VoteSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoteSummary(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoteSummary(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRoom(arg0: RoomCode): Promise<RoomView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyRooms(): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRooms();
            return result;
        }
    }
    async listRoomQuestions(arg0: RoomCode): Promise<Array<VoteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRoomQuestions(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRoomQuestions(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async raiseQuestion(arg0: RoomCode, arg1: string, arg2: string): Promise<RaiseResult> {
        if (this.processError) {
            try {
                const result = await this.actor.raiseQuestion(arg0, arg1, arg2);
                return from_candid_RaiseResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raiseQuestion(arg0, arg1, arg2);
            return from_candid_RaiseResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_QuestionResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionResult): QuestionResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RaiseResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RaiseResult): RaiseResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_VoteChoice_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteChoice): VoteChoice {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VoteResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteResult): VoteResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_VoteStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteStatus): VoteStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_VoteSummary_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteSummary): VoteSummary {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomView]): RoomView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoteSummary]): VoteSummary | null {
    return value.length === 0 ? null : from_candid_VoteSummary_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoteChoice]): VoteChoice | null {
    return value.length === 0 ? null : from_candid_VoteChoice_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VoteStatus;
    title: string;
    yesPercent: bigint;
    noCount: bigint;
    totalVotes: bigint;
    yesCount: bigint;
    description: string;
    myVote: [] | [_VoteChoice];
    questionId: _QuestionId;
    noPercent: bigint;
    selectedSubmission: [] | [_UserId];
}): {
    status: VoteStatus;
    title: string;
    yesPercent: bigint;
    noCount: bigint;
    totalVotes: bigint;
    yesCount: bigint;
    description: string;
    myVote?: VoteChoice;
    questionId: QuestionId;
    noPercent: bigint;
    selectedSubmission?: UserId;
} {
    return {
        status: from_candid_VoteStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        yesPercent: value.yesPercent,
        noCount: value.noCount,
        totalVotes: value.totalVotes,
        yesCount: value.yesCount,
        description: value.description,
        myVote: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.myVote)),
        questionId: value.questionId,
        noPercent: value.noPercent,
        selectedSubmission: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.selectedSubmission))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    status: _VoteStatus;
    title: string;
    description: string;
    closedAt: [] | [_Timestamp];
    raisedAt: _Timestamp;
    raisedBy: _UserId;
    selectedSubmission: [] | [_UserId];
    roomCode: _RoomCode;
}): {
    id: QuestionId;
    status: VoteStatus;
    title: string;
    description: string;
    closedAt?: Timestamp;
    raisedAt: Timestamp;
    raisedBy: UserId;
    selectedSubmission?: UserId;
    roomCode: RoomCode;
} {
    return {
        id: value.id,
        status: from_candid_VoteStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        closedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.closedAt)),
        raisedAt: value.raisedAt,
        raisedBy: value.raisedBy,
        selectedSubmission: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.selectedSubmission)),
        roomCode: value.roomCode
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): VoteStatus {
    return "closed" in value ? VoteStatus.closed : "open" in value ? VoteStatus.open : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    no: null;
} | {
    yes: null;
}): VoteChoice {
    return "no" in value ? VoteChoice.no : "yes" in value ? VoteChoice.yes : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    votingClosed: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): VoteResult {
    return "ok" in value ? VoteResult.ok : "votingClosed" in value ? VoteResult.votingClosed : "notFound" in value ? VoteResult.notFound : "unauthorized" in value ? VoteResult.unauthorized : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Question;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "ok";
    ok: Question;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Question_n7(_uploadFile, _downloadFile, value.ok)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoteSummary>): Array<VoteSummary> {
    return value.map((x)=>from_candid_VoteSummary_n15(_uploadFile, _downloadFile, x));
}
function to_candid_VoteChoice_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteChoice): _VoteChoice {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteChoice): {
    no: null;
} | {
    yes: null;
} {
    return value == VoteChoice.no ? {
        no: null
    } : value == VoteChoice.yes ? {
        yes: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
